spring.application.name=security

spring.datasource.url=jdbc:postgresql://localhost:5432/aprenderSecurity
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.show-sql=true